# Generated by Django 3.2.12 on 2023-09-06 21:07
import sys

from django.db import migrations
from django.conf import settings
from core.Utils.migration import load_fixture


def load_post_colors(apps, schema):
    if settings.TEST_MODE or 'test' in sys.argv:
        return

    PostColor = apps.get_model('Colors', 'PostColor')

    qs = PostColor.objects.all()
    if not qs.exists():
        load_fixture(apps, 'core/Colors/fixture/post_colors_6_sep_2023.json', 'Colors.PostColor')
        print('[+] Load Post color fixtures')
    else:
        raise ValueError('Post colors already exists!')


class Migration(migrations.Migration):
    dependencies = [
        ('Colors', '0002_load_category_colors'),
    ]

    operations = [
        migrations.RunPython(load_post_colors)
    ]
