# Generated by Django 3.2.12 on 2023-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
