# Generated by Django 3.2.12 on 2023-08-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserFeedback', '0002_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('commented', 'Commented')], default='new', max_length=16),
        ),
    ]
