# Generated by Django 3.2.12 on 2023-08-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='by_the_creator',
            field=models.BooleanField(default=False, verbose_name='Flag that the post was created by the author'),
        ),
    ]
