# Generated by Django 3.2.12 on 2023-08-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_by_the_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_data',
            field=models.JSONField(default=dict),
        ),
    ]
