# Generated by Django 3.2.12 on 2023-08-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_text_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='removed_stamp',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
