# Generated by Django 3.2.12 on 2023-09-02 10:23

import uuid
from django.db import migrations, models


def fill_id_with_uuid(apps, schema_editor):
    Post = apps.get_model('Post', 'Post')
    PostComment = apps.get_model('Post', 'PostComment')

    for item in Post.objects.all():
        old_obj_id = item.id

        qs = PostComment.objects.select_related('post').filter(post=item)
        item.id = uuid.uuid4()
        item.save()
        qs.update(model=item)

        Post.objects.filter(id=old_obj_id).first().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('Post', '0004_postcomment_removed_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(auto_created=True, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.RunPython(fill_id_with_uuid),
    ]
