# Generated by Django 3.2.12 on 2023-09-02 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Post', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.CharField(auto_created=True, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.RunSQL("delete from post_comment"),
    ]
