# Generated by Django 3.2.12 on 2023-09-02 10:20

import uuid
from django.db import migrations, models


def fill_id_with_uuid(apps, schema_editor):
    Subscription = apps.get_model('Subscription', 'Subscription')

    for item in Subscription.objects.all():
        old_obj_id = item.id
        item.id = uuid.uuid4()
        item.save()
        Subscription.objects.filter(id=old_obj_id).first().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.CharField(auto_created=True, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.RunPython(fill_id_with_uuid)
    ]
