# Generated by Django 3.2.12 on 2023-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrequest',
            name='working_experience',
            field=models.CharField(choices=[('0_2', '0-2'), ('2_4', '2-4'), ('5_plus', '5+')], max_length=20),
        ),
    ]
