# Generated by Django 3.2.12 on 2023-08-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorRequest', '0002_alter_authorrequest_working_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('reject', 'Rejected')], db_index=True, default='new', max_length=20),
        ),
    ]
