# Generated by Django 3.2.12 on 2023-08-26 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthorRequest', '0003_alter_authorrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorrequest',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
