# Generated by Django 3.2.12 on 2023-09-01 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorRequest', '0007_fill_id_with_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
