# Generated by Django 3.2.12 on 2023-09-01 21:01
import uuid
from django.db import migrations, models


def fill_id_with_uuid(apps, schema_editor):
    AuthorRequestComment = apps.get_model('AuthorRequest', 'AuthorRequestComment')

    for item in AuthorRequestComment.objects.all():
        old_obj_id = item.id
        item.id = uuid.uuid4()
        item.save()
        AuthorRequestComment.objects.filter(id=old_obj_id).first().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('AuthorRequest', '0008_alter_authorrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrequestcomment',
            name='id',
            field=models.CharField(auto_created=True, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.RunPython(fill_id_with_uuid)
    ]
